export const FETCH_NOTE_REQUEST = 'FETCH_NOTE_REQUEST';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE';
export const SAVE_NOTE = 'SAVE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const TOGGLE_DETAILS_ON = 'TOGGLE_DETAILS_ON';
export const TOGGLE_DETAILS_OFF = 'TOGGLE_DETAILS_OFF';
export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';